//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BTEFNhanVienPhongBanCongtyEntities : DbContext
    {
        public BTEFNhanVienPhongBanCongtyEntities()
            : base("name=BTEFNhanVienPhongBanCongtyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONGTY> CONGTies { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<phongban> phongbans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
